### ISSUE TITLE
lerna bootstrap not hoisting react react-dom and styled-components because of peerDependencies

### ISSUE THREAD

**Issue by canvay** [qubitsky/anya-ui#1]
根目录下执行lerna bootstrap --hoist后，

- react
- react-dom
- styled-components 

以上依赖同时被安装到了 `anya-ui/packages/components/node_modules` 和 `anya-ui/node_modules` 目录下
导致 `anya-ui/packages/demo` 应用在浏览器中运行时报错

去掉 `anya-ui/packages/components/package.json` 中的 peerDependencies 则正常，所以怀疑与 peerDependencies 有关

```shell
node -v
v17.7.2

npm -v
8.5.2
```

**Comment by canvay** [comment]
查阅到以下资料

> 在NPM v7中，现在默认安装peerDependencies。
> —— [【前端开发技巧】npm install xxxx --legacy-peer-deps到底做了些什么？](https://juejin.cn/post/6971268824288985118)

> If you're using npm 7+ now, you just have to add "useWorkspaces": true to your lerna.json as npm has similar behaviour to yarn now.
> —— https://github.com/lerna/lerna/issues/2822

**Comment by qubitsky** [comment]
[#004d3ab](https://github.com/qubitsky/anya-ui/commit/004d3abcabca90b540cbebbb6ae6cf30072a7a90)

**Comment by qubitsky** [comment]
https://github.com/qubitsky/anya-ui/commit/004d3abcabca90b540cbebbb6ae6cf30072a7a90
